### ISSUE TITLE
No positions for some identifiers

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/php-driver#33] opened 2019-03-21 10:41 UTC
repo git://github.com/denistrator/php-lessons-lesson-4 commit 92e13a6596b96bfb23f935377fa7f15a468e36cf file PHPPuzzle/Puzzle.php adds identifier canInputControlGameBoard with no position

repo git://github.com/denistrator/php-lessons-lesson-4 commit 92e13a6596b96bfb23f935377fa7f15a468e36cf file PHPPuzzle/Puzzle.php adds identifier swapGameChips with no position

repo git://github.com/denistrator/php-lessons-lesson-4 commit 9b3c5a18a07d4e1f190a82fcc8ce76412f29f057 file PHPPuzzle/Puzzle.php adds identifier getInputKey with no position

repo git://github.com/denistrator/php-lessons-lesson-4 commit 9b3c5a18a07d4e1f190a82fcc8ce76412f29f057 file PHPPuzzle/Puzzle.php removes identifier geuInputKey with no position

**Comment by dennwc** [comment] 2019-03-21 10:50
duplicate of https://github.com/bblfsh/php-driver/issues/19

**Closed by dennwc** 2019-03-21 10:50 UTC
